server:
  port: 80
doctors:
  host-name: localhost
  working-hours:
    startTime: 9
    endTime: 16
  specializations:
    -surgeon
    -cardiologist

spring:
  logging:
    level:
      sql: true

  flyway:
    baselineOnMigrate: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
pet-clinic:
  host-name: my-pet.com
  name: Aibolit
  working-hours:
    start:  8AM
    end: 5PM
  doctors-specializations:  surgeon, veterinarian, therapeutist
  doctor-url:  "http://localhost:8081"
  diploma-url: "http://localhost:8081"









