server.port: 80
doctors:
  host-name: my-pet.com
  name: Aibolit
  working-hours:
    start:  8AM
    end: 5PM
  specializations: surgeon,cardiologist,therapeutist
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect

      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    sql: true